# Generated by Django 5.1.3 on 2024-12-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
