# Generated by Django 5.1.3 on 2024-12-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='school.courses'),
        ),
    ]
