# Generated by Django 5.1.3 on 2024-12-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_departments_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturers',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='school.departments'),
        ),
    ]
