# Generated by Django 5.1.3 on 2024-12-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardians',
            name='active',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='guardians',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.students'),
        ),
        migrations.AlterField(
            model_name='students',
            name='active',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], max_length=6, null=True),
        ),
    ]
