# Generated by Django 5.1.3 on 2024-12-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_guardians_active_alter_guardians_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='desription',
            field=models.TextField(null=True),
        ),
    ]
