# Generated by Django 5.1.3 on 2024-12-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_students_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='desription',
            new_name='description',
        ),
    ]
