# Generated by Django 5.1.3 on 2024-12-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_desription_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(default='student123', max_length=150),
        ),
    ]
