# Generated by Django 5.1.3 on 2024-12-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_students_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='students',
            managers=[
            ],
        ),
    ]
